spring.application.name=springboot-rabbitmq-demo




#logging.level.org.springframework.integration=DEBUG
#logging.level.org.springframework.integration.ftp=DEBUG
#logging.level.org.apache.commons.net=DEBUG


management.endpoints.web.exposure.include=refresh

ftp.directories.ucdp=/20250211/UCDP/Fold,er1;/20250211/UCDP/Fold,err32;/20250211/UCDP/Fold,er3
ftp.directories.newsroom=/20250211/NewsRoom/Fold,er1;/20250211/NewsRoom/Fold,err32;/20250211/NewsRoom/Fold,er3
ftp.download.enabled=true

#spring.cache.type=caffeine
#spring.cache.caffeine.spec=maximumSize=500,expireAfterWrite=10m




